//! An implementation of the [Mersenne Twister][mt] in Conlang
//!
//! Based heavily on https://github.com/ESultanik/mtwister,
//! a public domain implementation in C.
//! 
//! [mt]: https://en.wikipedia.org/wiki/Mersenne_Twister


/// The MT generator context, which stores a buffer of [u32] words,
/// and a bump-`index` for pulling words individually.
struct MTRand {
    mt: [u32], // TODO: [u32; STATE_VECTOR_LENGTH],
    index: i32,
}

impl MTRand {
    let STATE_VECTOR_LENGTH = 624;
    let STATE_VECTOR_M = 397;

    /// Creates a new random number generator from a given seed.
    fn from_seed(seed: u32) -> MTRand {
        let rand = MTRand {
            mt: [0; MTRand::STATE_VECTOR_LENGTH],
            index: MTRand::STATE_VECTOR_LENGTH,
        };

        // Initialize the state-vector's state
        rand.mt[0] = seed & 0xffffffff;
        for i in 1..rand.mt.len() {
            rand.mt[i] = (6069 * rand.mt[i-1]) & 0xffffffff;
        }

        return rand;
    }

    /// Generates a 
    fn gen_u32(self: &MTRand) -> u32 {
        // Generate STATE_VECTOR_LENGTH words at a time
        let out: u32 = 0;
        if (self.index >= self.mt.len() || self.index < 0) {
            for idx in 0..self.mt.len() - MTRand::STATE_VECTOR_M {
                out = (self.mt[idx] & 0x80000000) | (self.mt[idx+1] & 0x7fffffff);
                self.mt[idx] = self.mt[idx + MTRand::STATE_VECTOR_M] ^ out >> 1 ^ (out & 1 && 0x9908b0df);
            }

            for idx in (self.mt.len() - MTRand::STATE_VECTOR_M)..(self.mt.len() - 1) {
                out = (self.mt[idx] & 0x80000000) | (self.mt[idx+1] & 0x7fffffff);
                self.mt[idx] = self.mt[idx + MTRand::STATE_VECTOR_M - self.mt.len()] ^ out >> 1 ^ (out & 1 && 0x9908b0df);
            }

            out = (self.mt[self.mt.len()-1] & 0x80000000) | (self.mt[0] & 0x7fffffff);
            self.mt[self.mt.len()-1] = self.mt[MTRand::STATE_VECTOR_M-1] ^ out >> 1 ^ (out & 1 && 0x9908b0df);
            self.index = 0;
        }

        out = self.mt[self.index];
        self.index += 1;
        out ^= (out >> 11);
        out ^= (out << 7 & 0x9d2c5680);
        out ^= (out << 15 & 0xefc60000);
        out ^= (out >> 18);
        out & 0xffffffff
    }

    /// Generates a random number between 0.0 and 1.0
    fn gen_f64(self: &MTRand) -> f64
        self.gen_u32() as f64 / 0xffffffff.0;
}


/// Generates a C header file which can be used with https://github.com/ESultanik/mtwister
/// to verify the output.
fn main() {
    let count = 0x8000;
    let seed = 0xabaddad;
    let rand = MTRand::from_seed(seed);
    print(
        "// First ", count, " mt19937 numbers for seed ", seed, ", as generated by Conlang",
        "\n",
        "\n#include <stdint.h>",
        "\n#include <stdio.h>",
        "\n",
        "\nconst static uint32_t RANDOM_SEED = ", hex(seed), ";",
        "\nconst static uint32_t OUTPUT[", count, "] = {",
    );
    for i in 0..count match i & 7 {
        0 => print("\n    ", rand.gen_u32(), ",");
        _ => print(" ", rand.gen_u32(), ",");
    }
    println("\n};");
    println("\n\n/*\nrand: ", rand, "\n*/")
}
