[workspace]
members = [
    "compiler/cl-repl",
    "compiler/cl-typeck",
    "compiler/cl-interpret",
    "compiler/cl-structures",
    "compiler/cl-token",
    "compiler/cl-ast",
    "compiler/cl-parser",
    "compiler/cl-lexer",
    "repline",
]
resolver = "2"

[workspace.package]
repository = "https://github.com/boxdyn/conlang"
version = "0.0.9"
authors = ["John <j@soft.fish>"]
edition = "2024"
license = "MIT"
publish = ["soft-fish"]

[profile.dev]
opt-level = 1
