[workspace]
members = [
    "cl-repl",
    "cl-typeck",
    "cl-interpret",
    "cl-structures",
    "cl-token",
    "cl-ast",
    "cl-parser",
    "cl-lexer",
]
resolver = "2"

[workspace.package]
repository = "https://github.com/boxdyn/conlang"
version = "0.0.3"
authors = ["John <j@soft.fish>"]
edition = "2021"
license = "MIT"
publish = ["soft-fish"]
