[workspace]
members = [
    "compiler/cl-repl",
    "compiler/cl-typeck",
    "compiler/cl-interpret",
    "compiler/cl-structures",
    "compiler/cl-token",
    "compiler/cl-ast",
    "compiler/cl-parser",
    "compiler/cl-lexer",
]
resolver = "2"

[workspace.package]
repository = "https://github.com/boxdyn/conlang"
version = "0.11.0"
authors = ["John <j@soft.fish>"]
edition = "2024"
license = "MIT"
publish = ["soft-fish"]

[profile.dev]
opt-level = 1

[package]
name = "conlang"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
# cl-repl = { path = "compiler/cl-repl" }
# cl-typeck = { path = "compiler/cl-typeck" }
# cl-interpret = { path = "compiler/cl-interpret" }
cl-structures = { path = "compiler/cl-structures" }
cl-token = { path = "compiler/cl-token" }
cl-ast = { path = "compiler/cl-ast" }
cl-parser = { path = "compiler/cl-parser" }
cl-lexer = { path = "compiler/cl-lexer" }
repline = "0"
