(* Conlang Expression Grammar *)


Start = SOI Expr? EOI ;

(* Expressions *)

Expr = InAttr Expr | ExprDo ;
(* Not pictured: semicolon elision after block exprs *)
ExprDo = (ExprBody? ';')+ ExprBody? | ExprBody ;
ExprBody = ExprAssign ;
ExprAssign = ExprMake (AssignOp ExprMake)* ;
AssignOp = (
    '='  | '*=' | '/='  | '%='
  | '+=' | '-=' | '<<=' | '>>='
  | '&=' | '^=' | '|='
);
(* Hack: grammar is context-sensitive. Parser uses look-behind to disambiguate *)
ExprMake = !(Path '{') ExprTuple | Path '{' (MakeArm ',')* MakeArm? '}' ;
MakeArm = Identifier (':' ExprLogical)? ;
ExprTuple = ExprLogical (',' ExprLogical)* ;
ExprLogical = ExprLogOr ('^^' ExprLogOr)* ;
ExprLogOr = ExprLogAnd ('||' ExprLogAnd)* ;
ExprLogAnd = ExprCompare ('&&' ExprCompare)* ;
ExprCompare = ExprRange (('<=' | '!=' | '==' | '>=' | '<' | '>') ExprRange)*;
ExprRange = (
    ExprBinary? ('..' | '..=') ExprBinary?
  | ExprBinary
);
ExprBinary = ExprShift (('&' | '|' | '^') ExprShift)*;
ExprShift = ExprFactor (('<<' | '>>') ExprFactor)?;
ExprFactor = ExprTerm (('+' | '-') ExprTerm)*;
ExprTerm = ExprUnary (('*' | '/' | '%') ExprUnary)*;
ExprUnary = (
    ExprProject ('as' ExprProject)?
  | ('&' | '&&') ExprProject      (* Ref, DoubleRef *)
  | ('!' | '!!') ExprProject      (* Not, Identity *)
  | ('-' | '+' | '*') ExprProject (* Neg, Identity, Deref *)
);
(* hack: Pest, which I'm validating this with, doesn't know '..' is better than '.' *)
ExprProject = ExprExtend (!'..' '.' ExprExtend | '[' Expr? ']')* ;
ExprExtend = ExprMax ('(' Expr? ')')* ;

ExprMax = (
    Literal
  | "do" Expr
  | ("pub" | "const" | "static") ExprMax
  | ("loop" | "defer" | "break" | "return") ExprBody
  | ("if" | "while") ExprLogical ExprBody ("else" ExprBody)?
  | "continue"
  | '`' Expr? '`'
  | '{' Expr? '}'
  | '(' Expr? ')'
  | '[' ExprTuple? ']'
  | '[' ExprTuple (';' ExprTuple)? ']'
  | "use" Use
  | '$' Token
  | OutAttr ExprMax
  | InAttr Expr (* FIXME: move this *)
  | Match
  | Bind
  | Omitted
  | Path
);
Omitted = '...' ;

Match = "match" ExprTuple '{' (MatchArm ';')* MatchArm? '}' ;
MatchArm = Pat '=>' ExprBody ;

Bind = BindLet | BindType | BindStruct | BindEnum | BindFn | BindMod | BindImpl | BindFor ;
BindLet    = "let"    BoundGeneric? PatTuple ('=' ExprTuple   ("else" ExprBody)?)? ;
BindType   = "type"   BoundGeneric? PatAlt   ('=' ExprTuple)? ;
BindStruct = "struct" BoundGeneric? PatTuple ;
BindEnum   = "enum"   BoundGeneric? PatTuple ;
BindFn     = "fn"     BoundGeneric? PatFn    ('='? ExprBody) ;
BindMod    = "mod"    BoundGeneric? PatMax   ('='? ExprBody) ;
BindImpl   = "impl"   BoundGeneric? PatFn    ('='? ExprBody) ;
BindFor    = "for"    PatTuple "in" ExprLogical ExprBody ("else" ExprBody)? ;

BoundGeneric = '<' (Pat ',')* Pat? '>' ;

(* Patterns *)

Pat = PatAlt ;
PatAlt = '|'? PatTuple ('|' PatTuple)* ;
PatTuple = PatTyped (',' PatTyped)* ;
PatTyped = Attr? (
    '{' (PatTyped ',')* PatTyped? '}'
  | PatFn '{' (PatTyped ',')* PatTyped? '}'
  | PatFn ':' PatTyped
  | PatFn
);
PatFn = (
    PatParams
  | "fn" PatFn
  | '&' PatFn
  | '&&' PatFn
  | PatRange PatGenerics* PatParams? PatGuard? ('->' PatFn)?
);
PatGenerics = '<' (PatTyped ',')* PatTyped? '>' ;
PatParams = '(' (PatTyped ',')* PatTyped? ')' ;
PatGuard = 'if' ExprLogical ;

PatRange = (
    PatMax? '..' PatMax?
  | PatMax? '..=' PatMax?
  | PatMax
);
PatMax = (
    '[' PatTuple (';' PatTuple)? ']' (* Slices and Arrays*)
  | "pub" PatMax                     (* Publicity  *)
  | "mut" PatMax                     (* Mutability *)
  | '*' PatMax                       (* Ptr *)
  | '$' Token                        (* Metaidentifier *)
  | '!'                              (* Never *)
  | '_'                              (* Wildcard *)
  | '$' Token                        (* Metaidentifier *)
  | Identifier                       (* Binding wildcard *)
  | PatConst                         (* Constant expression *)
);
PatConst = (
    Literal
  | "const" Expr
  | '-' Expr
  | Path
);

(* Other AST nodes *)

Attr = InAttr | OutAttr ;
InAttr = '#!' '[' Expr ']' | InDoc;
OutAttr = '#' '[' Expr ']' | OutDoc;

Path = '::'? Identifier ('::' Identifier)* ;

Literal = (
    "true" | "false"
  | Character
  | Integer
  | String
);

Use = (
    '*'
  | '{' (Use ',')* Use? '}'
  | Identifier '::' Use
  | Identifier "as" Identifier
  | Identifier
);
