[package]
name = "cl-typeck"
repository.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
cl-ast = { path = "../cl-ast" }
cl-structures = { path = "../cl-structures" }

[dev-dependencies]
repline = { version = "*", registry = "soft-fish" }
cl-lexer = { path = "../cl-lexer" }
cl-parser = { path = "../cl-parser" }
