[package]
name = "cl-typeck"
description = "The Conlang Semantic Analyzer"
repository.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = ["bin"]
bin = ["dep:repline", "dep:cl-lexer", "dep:cl-parser"]

[dependencies]
cl-ast = { path = "../cl-ast" }
cl-structures = { path = "../cl-structures" }
repline = { version = "*", optional = true }
cl-lexer = { path = "../cl-lexer", optional = true }
cl-parser = { path = "../cl-parser", optional = true }

[[bin]]
name = "typeck"
path = "src/bin/typeck.rs"
required-features = ["bin"]
