[package]
name = "cl-typeck"
description = "The Conlang Semantic Analyzer"
repository.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
cl-ast = { path = "../cl-ast" }
cl-structures = { path = "../cl-structures" }

[dev-dependencies]
repline = "*"
cl-lexer = { path = "../cl-lexer" }
cl-parser = { path = "../cl-parser" }
