[package]
name = "conlang"
description = "The Conlang Programming Language"
keywords = ["interpreter", "programming", "language"]
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-xid = "0.2.4"
cl-structures = { path = "../cl-structures" }
